install:
	npm install

generate-keys:
	npm run generate:vapid

dev:
	npm run dev

build:
	npm run build

start:
	npm run build && npm run start

clean:
	rm -rf dist node_modules data/subscriptions.db
